export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const CHANGE_AUTHENTICATED = 'CHANGE_AUTHENTICATED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_REGISTER = 'AUTH_REGISTER';
