branch-defaults:
  staging:
    environment: rappdio-frontend-staging
    group_suffix: null
global:
  application_name: rapidscoper-frontend
  branch: null
  default_ec2_keyname: mozzler
  default_platform: Node.js
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
